# Generated by Django 5.2.3 on 2025-07-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='like',
            new_name='board_like_user_348a97_idx',
            old_name='board_like_user_id_e3fc4d_idx',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.IntegerField(),
        ),
    ]
