# Generated by Django 5.2.3 on 2025-07-30 03:03

import board.utils.file_uploader
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_board_like_user_id_e3fc4d_idx_board_like_user_348a97_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(db_index=True, default='test@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(db_index=True, default='test@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=board.utils.file_uploader.post_thumbnail_upload_to),
        ),
    ]
